### ISSUE TITLE
Dask on  kubernetes

### ISSUE THREAD

**Issue by devopsdymyr** [castares/movie-time#1]
I have trying to deploy my code to kubernetes dask.
Can you guild me how to do.

I have deployed in kubernetes with help of helm chart  [https://docs.dask.org/en/latest/setup/kubernetes.html]

i am able to test code with sample 
![Screenshot from 2020-01-29 16-53-42](https://user-images.githubusercontent.com/41105507/73352813-f4b25e00-42b7-11ea-87f6-7f46dd4df966.png)

i am confused on test our model file worker image and test

**Comment by castares** [comment]
Sorry, but I don't think I can help. I recommend you to open an issue on Dask's repo: <https://github.com/dask/dask> specifying the error you are receiving.
